---
- name: Copy HTML Template mit Handler
  hosts: all
  become: true
  vars:
          apache_webroot: /var/www/html

  tasks:
          - name: "Copy html Datei"
            template:
                    src: templates/index.html.j2
                    dest: "{{ apache_webroot }}/index.html"
                    mode: 0644
            notify: Restart Apache

  handlers:
          - name: Restart Apache
            service:
                    name: apache2
                    state: restarted
